* My Emacs configuration
  I like modal editing and Vim's keybindings. I also really like Lisp and the unparalleled extensibility that it enables in Emacs. This is my attempt to combine (what I consider to be) the advantages of both editors.

  Note that it is written with my particular use-cases in mind (for example, the keybindings are optimized for the [[http://www.kaufmann.no/roland/dvorak/][Programmer Dvorak]] keyboard layout). You probably don't want to use this configuration verbatim. Instead, copy parts of it into your own.

** Compatibility
   Requires *Emacs 24.3* or newer.

** Installation
   Just clone this repository into =~/.emacs.d=. On the first launch, Emacs will download and install all the necessary packages into =~/.emacs.d/elpa=.

** Some of the packages used
   - =evil= :: By far the best Vim emulation that I know of. Elegant code. More customizable than Vim itself.
   - =ido=, =ido-ubiquitous=, =smex=, =flx-ido= :: Fuzzy completion in the minibuffer.
   - =smartparens= :: Provides shortcuts for manipulating entire s-expressions at once. Less strict than =paredit=, and its usefulness is not limited to Lisps.
   - =auto-complete=, =yasnippet= :: Completion menu with snippets. I use =auto-complete= over =company-mode= mostly because of inertia.
