* My Emacs configuration
  I like modal editing and Vim's keybindings. I also really like Lisp and the extensibility it enables in Emacs. This is my attempt to combine (what I consider to be) the advantages of both editors.

  Note that it is written with my particular use-cases in mind (for example, keybindings are optimized for the [[http://www.kaufmann.no/roland/dvorak/][Programmer Dvorak]] keyboard layout). You probably don't want to use this configuration verbatim; instead, copy parts of it into your own.

** Compatibility
   Requires *Emacs 24.3* or newer.

** Installation
   Just clone this repository into =~/.emacs.d=. On the first launch, Emacs will download and install all the necessary packages into =~/.emacs.d/elpa=.

** Some of the packages used
   - =evil= :: Most comprehensive Vim emulation I've ever seen.
   - =ido=, =ido-ubiquitous=, =smex=, =flx-ido= :: Fuzzy completion in the minibuffer.
   - =smartparens= :: Manipulating entire s-expressions at once. Less strict than =paredit=, and useful outside of Lisps.
   - =auto-complete=, =yasnippet= :: Completion menu with snippets. I use =auto-complete= instead of =company-mode= mostly because of inertia.
   - =flycheck= :: On-the-fly syntax checking.
   - =magit= :: An efficient and convenient Git interface.
   - =use-package= :: Syntactic sugar that simplifies package configuration.
   - =cedet=, =srefactor= :: Language-aware features.
