;;; `require' my customizations based on some conditions.

;; The order of these `require's must not be significant.
;; (They are treated as a DAG by my `flatten-conf' utility.)

(require 'conf/evil)

(require 'conf/view/trailing-whitespace)
(require 'conf/view/indent-guides)
(require 'conf/view/hl-current-line)
(require 'conf/view/color-theme)
(require 'conf/view/color-identifiers)
(require 'conf/view/wrapping)
(require 'conf/view/scrolling)
(require 'conf/view/ui-elements)
(require 'conf/view/page-break-lines)
(require 'conf/view/initial-messages)
(require 'conf/view/windows/automatic-window-splitting)
(require 'conf/view/windows/window-bindings)
(require 'conf/view/buffers/unique-buffer-names)
(require 'conf/view/buffers/buffer-bindings)
(require 'conf/view/modeline/background)
(require 'conf/view/modeline/format)

(when (display-graphic-p)
  (require 'conf/view/gui/title)
  (require 'conf/view/gui/font)
  (require 'conf/view/gui/cursor)
  (require 'conf/view/gui/fringe)
  (require 'conf/view/gui/start-maximized)
  (require 'conf/view/gui/focus-follows-mouse))

(require 'conf/minibuffer/confirmations)
(require 'conf/minibuffer/ido)
(require 'conf/minibuffer/M-x)
(require 'conf/minibuffer/default-choice)

(require 'conf/visual/search-selected)
(require 'conf/visual/expand-region)
(require 'conf/visual/undo-in-region)
(require 'conf/visual/text-object-whole-buffer)

(require 'conf/insert-state/insert-verbatim)
(require 'conf/insert-state/exit-insert-state)

(require 'conf/moving/little-word)
(require 'conf/moving/marks-registers)
(require 'conf/moving/vim-dvorak)
(require 'conf/moving/passthrough-keys)
(require 'conf/moving/ace-jump)

(require 'conf/editing/indentation)
(require 'conf/editing/refactoring)
(require 'conf/editing/completion)
(require 'conf/editing/comments)
(require 'conf/editing/smartparens)
(require 'conf/editing/snippets)
(require 'conf/editing/insert-newline)
(require 'conf/editing/break-line)
(require 'conf/editing/inc-dec-number)
(require 'conf/editing/hungry-delete)

(require 'conf/driving-processes/ag)
(require 'conf/driving-processes/isend)
(require 'conf/driving-processes/version-control)
(require 'conf/driving-processes/compiling)

(require 'conf/opening-saving/backups)
(require 'conf/opening-saving/cygwin)
(require 'conf/opening-saving/tramp)
(require 'conf/opening-saving/move-delete)
(require 'conf/opening-saving/auto-revert)
(require 'conf/opening-saving/auto-save)
(require 'conf/opening-saving/editorconfig)
(require 'conf/opening-saving/encoding)
(require 'conf/opening-saving/save-point-position)
(require 'conf/opening-saving/bindings)
(require 'conf/opening-saving/ido)
(require 'conf/opening-saving/vim-modelines)
(require 'conf/opening-saving/recent-files)
(require 'conf/opening-saving/diff)

(require 'conf/configuring/unbound)
(require 'conf/configuring/flatten-conf)
(require 'conf/configuring/command-log)

(require 'conf/other/enable-confusing-commands)
(require 'conf/other/portable-keyboard-layout-fix)
(require 'conf/other/guide-key)
(require 'conf/other/convenient-prefix-keys)
(require 'conf/other/clipboard)
(require 'conf/other/count-lines-words-chars)
(require 'conf/other/prefix-arguments)
(require 'conf/other/yank)
(require 'conf/other/pastebin)

(require 'conf/mode-specific/fundamental)
(require 'conf/mode-specific/c-and-c++)
(require 'conf/mode-specific/calc)
(require 'conf/mode-specific/compilation)
(require 'conf/mode-specific/org)
(require 'conf/mode-specific/vimrc)
(require 'conf/mode-specific/elisp-and-interaction)
(require 'conf/mode-specific/lisps)
(require 'conf/mode-specific/latex)
(require 'conf/mode-specific/scala)
(require 'conf/mode-specific/sgml)
(require 'conf/mode-specific/pascal)
(require 'conf/mode-specific/puppet)
(require 'conf/mode-specific/asciidoc)
(require 'conf/mode-specific/term)
(require 'conf/mode-specific/bat-cmd)

(provide 'conf/main)
